baseURL = "http://oscardealva.com/"
languageCode = "en-us"
title = "Oscar De Alva"
theme = "personal-web"
copyright = "© Oscar De Alva"
googleAnalytics = ""
enableEmoji = true
enableRobotsTXT = true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Oscar :wave:"
  sub = "I'm a new graduate of CS Engineering and aspiring Data Engineer."

[params.main]
  latestPublishHeader = "My Latest Project"

[taxonomies]
  design = "designs"
  tech = "techs"

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio']

[params.notFound]
  gopher = "/images/gopher.png"
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  post = "article"
  portfolio = "project"

[params.social]
  github = "https://github.com/"
  linkedin = "https://www.linkedin.com/in/"
  medium = "https://medium.com/"
  hackerrank = "https://hackerrank.com/"

[params.sidebar]
  backgroundImage = "images/sidebar.jpg"

#[params.contact]
#  email = "oscar.ivan98@gmail.com"
#  text= "Feel free to contact me"

[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "resume"
  name = "Resume"
  title = "Resume"
  url = "/resume/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false

